version: '3.7'

x-vault-base: &vault_base
  image: vault:1.2.3
  cap_add:
    - IPC_LOCK

services:
  vault-dev:
    <<: *vault_base
    ports: ['1234:1234']
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: myroot
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:1234

  vault:
    <<: *vault_base
    ports: ['8200:8200']
    environment:
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_API_ADDR: https://0.0.0.0:8200
    command: server
    volumes:
      - ./vault/config/:/vault/config/
      - vault_data:/vault/

volumes:
  vault_data: {}
